// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.17.3
// source: tcp/tcp_rpc.proto

package tcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *HelloMsg) Reset() {
	*x = HelloMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcp_tcp_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloMsg) ProtoMessage() {}

func (x *HelloMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_tcp_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloMsg.ProtoReflect.Descriptor instead.
func (*HelloMsg) Descriptor() ([]byte, []int) {
	return file_tcp_tcp_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *HelloMsg) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type OK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *OK) Reset() {
	*x = OK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcp_tcp_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OK) ProtoMessage() {}

func (x *OK) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_tcp_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OK.ProtoReflect.Descriptor instead.
func (*OK) Descriptor() ([]byte, []int) {
	return file_tcp_tcp_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *OK) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OK) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc      string `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	Pwd      string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Photo    string `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"`
	Userid   int32  `protobuf:"varint,5,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *UserMsg) Reset() {
	*x = UserMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcp_tcp_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMsg) ProtoMessage() {}

func (x *UserMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_tcp_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMsg.ProtoReflect.Descriptor instead.
func (*UserMsg) Descriptor() ([]byte, []int) {
	return file_tcp_tcp_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *UserMsg) GetAcc() string {
	if x != nil {
		return x.Acc
	}
	return ""
}

func (x *UserMsg) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *UserMsg) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserMsg) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *UserMsg) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

var File_tcp_tcp_rpc_proto protoreflect.FileDescriptor

var file_tcp_tcp_rpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x63, 0x70, 0x2f, 0x74, 0x63, 0x70, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x63, 0x70, 0x22, 0x26, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x22, 0x2c, 0x0a, 0x02, 0x4f, 0x4b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x77,
	0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x63, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x32, 0xb1, 0x01, 0x0a, 0x06, 0x54, 0x43, 0x50, 0x52,
	0x50, 0x43, 0x12, 0x27, 0x0a, 0x0b, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x43, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x12, 0x0d, 0x2e, 0x74, 0x63, 0x70, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x73, 0x67,
	0x1a, 0x07, 0x2e, 0x74, 0x63, 0x70, 0x2e, 0x4f, 0x4b, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0b, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0c, 0x2e, 0x74, 0x63, 0x70,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x1a, 0x0c, 0x2e, 0x74, 0x63, 0x70, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0e, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0c, 0x2e, 0x74, 0x63, 0x70,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x1a, 0x07, 0x2e, 0x74, 0x63, 0x70, 0x2e, 0x4f,
	0x4b, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x43, 0x61, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x0c, 0x2e, 0x74, 0x63, 0x70, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x1a, 0x07, 0x2e, 0x74, 0x63, 0x70, 0x2e, 0x4f, 0x4b, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f,
	0x74, 0x63, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tcp_tcp_rpc_proto_rawDescOnce sync.Once
	file_tcp_tcp_rpc_proto_rawDescData = file_tcp_tcp_rpc_proto_rawDesc
)

func file_tcp_tcp_rpc_proto_rawDescGZIP() []byte {
	file_tcp_tcp_rpc_proto_rawDescOnce.Do(func() {
		file_tcp_tcp_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_tcp_tcp_rpc_proto_rawDescData)
	})
	return file_tcp_tcp_rpc_proto_rawDescData
}

var file_tcp_tcp_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tcp_tcp_rpc_proto_goTypes = []interface{}{
	(*HelloMsg)(nil), // 0: tcp.HelloMsg
	(*OK)(nil),       // 1: tcp.OK
	(*UserMsg)(nil),  // 2: tcp.UserMsg
}
var file_tcp_tcp_rpc_proto_depIdxs = []int32{
	0, // 0: tcp.TCPRPC.HelloCaller:input_type -> tcp.HelloMsg
	2, // 1: tcp.TCPRPC.LoginCaller:input_type -> tcp.UserMsg
	2, // 2: tcp.TCPRPC.NicknameCaller:input_type -> tcp.UserMsg
	2, // 3: tcp.TCPRPC.PhotoCaller:input_type -> tcp.UserMsg
	1, // 4: tcp.TCPRPC.HelloCaller:output_type -> tcp.OK
	2, // 5: tcp.TCPRPC.LoginCaller:output_type -> tcp.UserMsg
	1, // 6: tcp.TCPRPC.NicknameCaller:output_type -> tcp.OK
	1, // 7: tcp.TCPRPC.PhotoCaller:output_type -> tcp.OK
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcp_tcp_rpc_proto_init() }
func file_tcp_tcp_rpc_proto_init() {
	if File_tcp_tcp_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tcp_tcp_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tcp_tcp_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tcp_tcp_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tcp_tcp_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tcp_tcp_rpc_proto_goTypes,
		DependencyIndexes: file_tcp_tcp_rpc_proto_depIdxs,
		MessageInfos:      file_tcp_tcp_rpc_proto_msgTypes,
	}.Build()
	File_tcp_tcp_rpc_proto = out.File
	file_tcp_tcp_rpc_proto_rawDesc = nil
	file_tcp_tcp_rpc_proto_goTypes = nil
	file_tcp_tcp_rpc_proto_depIdxs = nil
}
